theme: jekyll-theme-minimal
title: Anshu Grewal 
<img src="https://github.com/anshugrewal/anshugrewal.github.io/blob/main/profile.jpg" alt="Anshu Grewal" width="150" style="border-radius: 50%; display: block; margin: auto;">
description: Bookmark this to keep an eye on my project updates!
